language: python
sudo: false
python:
- 3.6
- 3.7
- 3.8

install:
- pip install -U setuptools
- pip install -r requirements-dev.txt
- pip install -e .
- pip install -U uvloop
- pip install codecov

script:
- make cov
after_success:
- codecov

deploy:
  provider: pypi
  user: __token__
  password:
    secure: C4ap//nLGJrl8LDQtHTQEtq6l+CGt7RxZLw23GYCxV+Ljuo5mtQ1NrFU4hCvENQzNVS3NV0kf0h7geGpR51BfTuEDPwekzWw04dpVCzLlqFrYxVRZ9rFHmlQSgVHeExe7XPCYs9+UqFgM0ghzTkq37hr0AqMlO5FXi1LgGCm/fs+NVZccn9g5neqRGXM9zRLKdcUeRr86AJDSNcCFjJtu5VNaSpv9qYbWeT5gfxV0pZ5mF9aDtlNsMzjqXLcNTfL30Kjf1WxK3javtIE5MYy1BNuvJPjLlvo/bg4blonFsZsDp2lCmJKLIYo/sw42RaNU1rLSuLKM2nt+G/vFHhTE6SY8XpsS6hQd4w7FeFsLdogKFyETzM+QHjZgQqkmq/3YE7xW0fEUp3BqYcIDvbR3cnpo4BUX5fAMyWvDgOTHugQxAKNio7A7IoL3fagBXZKGGBacRzsZlT3+A1XJQfQAmv5vVcar2gywT08paGtektbE8M8P4pk5YfxfRrI0LwvMJjczkZ/qepGQp/ohK4VWDDPhOxI5fmCUYD0M0H2vxj3FeQZQjwfUlTbUWIY5ybW/Jd5AJKM0srJit+agG2IpoL2omUAHRwTIpAqH2mA46LtZa5BOvoOWkEFGOgxqCsYp3UeOQ94A4/olC2PllE8aktafwbucj3N3Jm/5WWkBTE=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.7
